# Ingress definition
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /stats(/|$)(.*)
            backend:
              service:
                name: aspire-dashboard
                port:
                  number: 1888
          - pathType: Prefix
            path: /
            backend:
              service:
                name: webfrontend
                port:
                  number: 8080