name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check client id
        run: echo ${{ secrets.TAILSCALE_OAUTH_CLIENT }}
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          #authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:gh1
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      - name: Wait for 10s
        run: sleep 10
      - name: Ping ip
        run: ping 10.1.0.10

