name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t dotnetexperiments .
          docker tag abdullahi1/dotnetexperiments

      - name: Run Docker container
        run: docker run -d -p 5000:5000 dotnetexperiments

      - name: Wait for container to start
        run: sleep 5

      - name: Test Docker container
        run: curl -s http://localhost:5000/hello || exit 1      
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      # Push the Docker image
      - name: Push Docker image to registry
        run: docker push abdullahi1/dotnetexperiments:main

      - name: Check client id
        run: echo ${{ secrets.TAILSCALE_OAUTH_CLIENT }}
        
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          tags: tag:ci
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      - name: Wait for 5s
        run: sleep 5
      - name: Ping ip
        run: ping -c 2 10.1.0.120 


        

