name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check client id
        run: echo ${{ secrets.TAILSCALE_OAUTH_CLIENT }}
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          tags: tag:ci
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      - name: Wait for 5s
        run: sleep 5
      - name: Ping ip
        run: ping -c 2 10.1.0.10 

